{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "from matplotlib.animation import FuncAnimation\n",
    "import numpy as np\n",
    "\n",
    "%matplotlib widget"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Overwriting auto display for cadquery Workplane and Shape\n"
     ]
    }
   ],
   "source": [
    "import cadquery as cq\n",
    "from jupyter_cadquery.cadquery import (PartGroup, Part, Edges, Faces, Vertices, show, \n",
    "                                       replay, enable_replay, disable_replay, reset_replay)\n",
    "\n",
    "from jupyter_cadquery import set_sidecar, set_defaults\n",
    "show_object = show"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "set_sidecar(\"Gears\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## **Utility functions**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "def sphere_to_cartesian(r, gamma, theta):\n",
    "    '''Convert spherical coordinates to cartesian\n",
    "       r - sphere radius\n",
    "       gamma - polar angle\n",
    "       theta - azimuth angle\n",
    "       return - cartesian coordinates\n",
    "    '''\n",
    "    return (r * np.sin(gamma) * np.sin(theta),\n",
    "            r * np.sin(gamma) * np.cos(theta),\n",
    "            r * np.cos(gamma))\n",
    "\n",
    "def s_arc(sr, c_gamma, c_theta, r_delta, start, end, n=32):\n",
    "    '''Get arc points plotted on a sphere's surface\n",
    "       sr - sphere radius\n",
    "       c_gamma - polar angle of the circle's center\n",
    "       c_theta - azimuth angle of the circle's center\n",
    "       r_delta - angle between OC and OP, where O is sphere's center,\n",
    "                 C is the circle's center, P is any point on the circle\n",
    "       start - arc start angle\n",
    "       end - arc end angle\n",
    "       n - number of points\n",
    "       return - circle points\n",
    "    '''\n",
    "    t = np.expand_dims(np.linspace(start, end, n), axis=1)\n",
    "    a = sphere_to_cartesian(1.0, c_gamma + r_delta, c_theta)\n",
    "    k = sphere_to_cartesian(1.0, c_gamma, c_theta)\n",
    "    c = np.cos(t) * a + np.sin(t) * np.cross(k, a) + \\\n",
    "        np.dot(k, a) * (1.0 - np.cos(t)) * k\n",
    "    c = c * sr\n",
    "    return [dim.squeeze() for dim in np.hsplit(c, 3)]\n",
    "\n",
    "def s_inv(gamma0, gamma):\n",
    "    phi = np.arccos(np.tan(gamma0) / np.tan(gamma))    \n",
    "    return np.arccos(np.cos(gamma) / np.cos(gamma0)) / np.sin(gamma0) - phi\n",
    "\n",
    "\n",
    "def circle3d_by3points(a, b, c):\n",
    "    u = b - a\n",
    "    w = np.cross(c - a, u)\n",
    "    u = u / np.linalg.norm(u)\n",
    "    w = w / np.linalg.norm(w)\n",
    "    v = np.cross(w, u)\n",
    "    \n",
    "    bx = np.dot(b - a, u)\n",
    "    cx, cy = np.dot(c - a, u), np.dot(c - a, v)\n",
    "    \n",
    "    h = ((cx - bx / 2.0) ** 2 + cy ** 2 - (bx / 2.0) ** 2) / (2.0 * cy)\n",
    "    cc = a + u * (bx / 2.0) + v * h\n",
    "    r = np.linalg.norm(a - cc)\n",
    "\n",
    "    return r, cc\n",
    "\n",
    "\n",
    "def rotation_matrix(axis, alpha):\n",
    "    ux, uy, uz = axis\n",
    "    sina, cosa = np.sin(alpha), np.cos(alpha)\n",
    "    r_mat = np.array((\n",
    "        (cosa + (1.0 - cosa) * ux ** 2,\n",
    "         ux * uy * (1.0 - cosa) - uz * sina,\n",
    "         ux * uz * (1.0 - cosa) + uy * sina),\n",
    "        (uy * ux * (1.0 - cosa) + uz * sina,\n",
    "         cosa + (1.0 - cosa) * uy ** 2,\n",
    "         uy * uz * (1.0 - cosa) - ux * sina),\n",
    "        (uz * ux * (1.0 - cosa) - uy * sina,\n",
    "         uz * uy * (1.0 - cosa) + ux * sina,\n",
    "         cosa + (1.0 - cosa) * uz ** 2),\n",
    "    ))\n",
    "\n",
    "    return r_mat\n",
    "\n",
    "\n",
    "def angle_between(o, a, b):\n",
    "    p = a - o\n",
    "    q = b - o\n",
    "    return np.arccos(np.dot(p, q) / (np.linalg.norm(p) * np.linalg.norm(q)))\n",
    "\n",
    "\n",
    "def project_to_xy_from_sphere_center(pts, sphere_r):\n",
    "    gammas = np.arccos(np.dot(pts, np.array((0.0, 0.0, 1.0))) / \\\n",
    "                       np.linalg.norm(pts, axis=1))\n",
    "    thetas = np.arctan2(pts[:, 0], pts[:, 1])\n",
    "    radiuses = sphere_r /  np.cos(gammas)\n",
    "    proj_pts = np.dstack(sphere_to_cartesian(radiuses,\n",
    "                                             gammas, thetas)).squeeze()\n",
    "    \n",
    "    return proj_pts\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## **OpenCascade utility functions**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {},
   "outputs": [],
   "source": [
    "from OCP.Precision import Precision\n",
    "from OCP.TColgp import TColgp_HArray2OfPnt, TColgp_HArray1OfPnt\n",
    "from OCP.GeomAPI import (GeomAPI_PointsToBSplineSurface,\n",
    "                         GeomAPI_PointsToBSpline)\n",
    "from OCP.BRepBuilderAPI import BRepBuilderAPI_MakeFace\n",
    "\n",
    "\n",
    "def make_spline_approx(points, tol=1e-2, smoothing=False, minDeg=1, maxDeg=3):\n",
    "    '''\n",
    "    Approximate a surface through the provided points.\n",
    "    '''\n",
    "    points_ = TColgp_HArray2OfPnt(1, len(points), 1, len(points[0]))\n",
    "\n",
    "    for i, vi in enumerate(points):\n",
    "        for j, v in enumerate(vi):\n",
    "            v = cq.Vector(*v)\n",
    "            points_.SetValue(i + 1, j + 1, v.toPnt())\n",
    "\n",
    "    if smoothing:\n",
    "        spline_builder = GeomAPI_PointsToBSplineSurface(\n",
    "            points_, *smoothing, DegMax=maxDeg, Tol3D=tol\n",
    "        )\n",
    "    else:\n",
    "        spline_builder = GeomAPI_PointsToBSplineSurface(\n",
    "            points_, DegMin=minDeg, DegMax=maxDeg, Tol3D=tol\n",
    "        )\n",
    "\n",
    "    if not spline_builder.IsDone():\n",
    "        raise ValueError(\"B-spline approximation failed\")\n",
    "\n",
    "    spline_geom = spline_builder.Surface()\n",
    "\n",
    "    return cq.Face(BRepBuilderAPI_MakeFace(spline_geom, Precision.Confusion_s()).Face())\n",
    "\n",
    "\n",
    "def make_spline_approx_1d(points, tol=1e-3, smoothing=None, minDeg=1, maxDeg=6):\n",
    "    '''\n",
    "    Approximate a spline through the provided points.\n",
    "    '''\n",
    "    points_ = TColgp_HArray1OfPnt(1, len(points))\n",
    "    \n",
    "    for ix, v in enumerate(points):\n",
    "        v = cq.Vector(*v)\n",
    "        points_.SetValue(ix + 1, v.toPnt())\n",
    "\n",
    "    if smoothing:\n",
    "        spline_builder = GeomAPI_PointsToBSpline(\n",
    "                            points_, *smoothing, DegMax=maxDeg, Tol3D=tol\n",
    "                         )\n",
    "    else:\n",
    "        spline_builder = GeomAPI_PointsToBSpline(\n",
    "                            points_, DegMin=minDeg, DegMax=maxDeg, Tol3D=tol\n",
    "                         )\n",
    "\n",
    "    if not spline_builder.IsDone():\n",
    "        raise ValueError(\"B-spline approximation failed\")\n",
    "\n",
    "    spline_geom = spline_builder.Curve()\n",
    "\n",
    "    return cq.Edge(BRepBuilderAPI_MakeEdge(spline_geom).Edge())\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## **Bevel gear**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 420,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Done, using side car 'Gears'\n"
     ]
    }
   ],
   "source": [
    "class BevelGear:    \n",
    "    def __init__(self, module=1.0, teeth_number=13,\n",
    "                 cone_angle=45.0, face_width=4.0, bore=6.0,\n",
    "                 pressure_angle=20.0, helix_angle=0.0,\n",
    "                 addendum_cf=1.0, dedendum_cf=1.25, curve_points=16):\n",
    "        m = module\n",
    "        self.z = z = teeth_number\n",
    "        self.curve_points = curve_points\n",
    "        self.face_width = face_width\n",
    "        self.bore = bore\n",
    "        ka = addendum_cf\n",
    "        kd = dedendum_cf\n",
    "        alpha = np.radians(pressure_angle)\n",
    "        \n",
    "        # pitch cone angle\n",
    "        self.gamma_p = gamma_p = np.radians(cone_angle)\n",
    "\n",
    "        # base/pitch circle radius\n",
    "        rp = m * z / 2.0\n",
    "        \n",
    "        # great sphere radius, also corresponds to pitch cone flank length\n",
    "        self.gs_r = gs_r = rp / np.sin(gamma_p) \n",
    "        \n",
    "        # angles of base, face and root cones \n",
    "        self.gamma_b = gamma_b = np.arcsin(np.cos(alpha) * np.sin(gamma_p))\n",
    "        self.gamma_f = gamma_f = gamma_p + np.arctan(ka * m / gs_r)\n",
    "        self.gamma_r = gamma_r = gamma_p - np.arctan(kd * m / gs_r)\n",
    "\n",
    "        phi_r = s_inv(gamma_b, gamma_p);\n",
    "        self.mirrpoint = mirrpoint = np.pi / z + 2.0 * phi_r\n",
    "                \n",
    "        self.tau = tau = np.pi * 2.0 / z\n",
    "        gamma_tr = max(gamma_b, gamma_r)\n",
    "\n",
    "        # Tooth left flank curve points\n",
    "        gamma = np.linspace(gamma_tr, gamma_f, curve_points)\n",
    "        theta = s_inv(gamma_b, gamma)\n",
    "        self.tooth_lflank = np.dstack(sphere_to_cartesian(gs_r,\n",
    "                                                          gamma,\n",
    "                                                          theta)).squeeze()\n",
    "        # Tooth tip curve points\n",
    "        theta_tip = np.linspace(theta[-1], mirrpoint - theta[-1], curve_points)\n",
    "        self.tooth_tip = np.dstack(sphere_to_cartesian(gs_r,\n",
    "                                                       np.full(curve_points,\n",
    "                                                               gamma_f),\n",
    "                                                       theta_tip)).squeeze()\n",
    "        # Tooth right flank curve points\n",
    "        self.tooth_rflank = np.dstack(\n",
    "                                sphere_to_cartesian(gs_r,\n",
    "                                                    gamma[::-1],\n",
    "                                                    mirrpoint - \\\n",
    "                                                        theta[::-1])).squeeze()\n",
    "\n",
    "        # Tooth root curve points\n",
    "        if gamma_r < gamma_b:\n",
    "            p1 = self.tooth_rflank[-1]\n",
    "            p2 = np.array(sphere_to_cartesian(gs_r, gamma_b, theta[0] + tau))\n",
    "            p3 = np.array(sphere_to_cartesian(gs_r, gamma_r,\n",
    "                                              (tau + mirrpoint) / 2.0))\n",
    "            rr, rcc = circle3d_by3points(p1, p2, p3)\n",
    "            rcc_gamma = np.arccos(np.dot(p3, rcc) / \\\n",
    "                                  (np.linalg.norm(p3) * np.linalg.norm(rcc)))\n",
    "            p1p3 = angle_between(rcc, p1, p3)\n",
    "            a_start = (np.pi - p1p3 * 2.0) / 2.0\n",
    "            a_end = -a_start + np.pi\n",
    "            self.tooth_root = np.dstack(s_arc(gs_r, gamma_r + rcc_gamma,\n",
    "                                              (tau + mirrpoint) / 2.0,\n",
    "                                              rcc_gamma,\n",
    "                                              np.pi / 2.0 + a_start,\n",
    "                                              np.pi / 2.0 + a_end,\n",
    "                                              curve_points)).squeeze()\n",
    "        else:\n",
    "            r_theta = np.linspace(mirrpoint - theta[0],\n",
    "                                  theta[0] + tau, curve_points)\n",
    "            self.tooth_root = np.dstack(sphere_to_cartesian(\n",
    "                                                        gs_r,\n",
    "                                                        np.full(curve_points,\n",
    "                                                                gamma_tr),\n",
    "                                                        r_theta)).squeeze()\n",
    "\n",
    "\n",
    "    def plot(self, plt_axes, sphere=True, pitch_circle=False,\n",
    "             base_circle=False, face_circle=False, root_circle=False,\n",
    "             t_matrix=None):\n",
    "        if t_matrix is None:\n",
    "            t_matrix = np.identity(3)\n",
    "        \n",
    "        tooth_pts = np.vstack((self.tooth_lflank, self.tooth_tip,\n",
    "                               self.tooth_rflank, self.tooth_root))\n",
    "        gear_pts = np.concatenate([\n",
    "                    tooth_pts @ rotation_matrix((0.0, 0.0, 1.0),\n",
    "                                                self.tau * i)\n",
    "                                   for i in range(self.z)]) @ t_matrix\n",
    "        \n",
    "        if sphere:\n",
    "            u = np.linspace(0.0, 2.0 * np.pi, 24)\n",
    "            v = np.linspace(0.0, np.pi, 24)\n",
    "            gs_x = self.gs_r * np.outer(np.cos(u), np.sin(v))\n",
    "            gs_y = self.gs_r * np.outer(np.sin(u), np.sin(v))\n",
    "            gs_z = self.gs_r * np.outer(np.ones(np.size(u)), np.cos(v))\n",
    "            ax.plot_surface(gs_x, gs_y, gs_z, color='#aaa', alpha=0.1)\n",
    "\n",
    "        c_points = self.curve_points * 2\n",
    "        t = np.linspace(0.0, np.pi * 2.0, c_points)\n",
    "        circles = ((pitch_circle , self.gamma_p, 'blue'),\n",
    "                   (base_circle, self.gamma_b, 'gray'),\n",
    "                   (face_circle, self.gamma_f, 'violet'),\n",
    "                   (root_circle, self.gamma_r, 'red'))\n",
    "        \n",
    "        for do_plot, gamma, color in circles:\n",
    "            if do_plot:\n",
    "                pts = np.dstack(sphere_to_cartesian(\n",
    "                                    np.full(c_points, self.gs_r),\n",
    "                                            gamma, t)).squeeze()\n",
    "                pts = pts @ t_matrix\n",
    "                x, y, z = (ax.squeeze() for ax in np.hsplit(pts, 3))\n",
    "                ax.plot3D(x, y, z, linestyle='dashed',\n",
    "                          linewidth=1.0, alpha=0.6, c=color)\n",
    "            \n",
    "        pts_x, pts_y, pts_z = (ax.squeeze() for ax in np.hsplit(gear_pts, 3))\n",
    "        plt_axes.plot3D(pts_x, pts_y, pts_z, linewidth=1.0, color='black')\n",
    "\n",
    "\n",
    "    def build(self):\n",
    "        \n",
    "        # build full cone gear faces\n",
    "        t_faces = []\n",
    "        \n",
    "        bottom_pos = np.cos(self.gamma_r) * self.gs_r\n",
    "        top_pos = np.cos(self.gamma_f) * (self.gs_r - self.face_width)\n",
    "        \n",
    "        for fpts in (self.tooth_lflank,\n",
    "                     self.tooth_tip,\n",
    "                     self.tooth_rflank,\n",
    "                     self.tooth_root):\n",
    "            edge_bottom = project_to_xy_from_sphere_center(fpts, bottom_pos)\n",
    "            edge_bottom[:, 2] = 0.0\n",
    "            \n",
    "            edge_top = project_to_xy_from_sphere_center(fpts, top_pos)\n",
    "            edge_top[:, 2] = bottom_pos - top_pos\n",
    "            \n",
    "            ppts = np.stack((edge_bottom, edge_top))\n",
    "            face = make_spline_approx(ppts)            \n",
    "            t_faces.append(face)\n",
    "            \n",
    "        faces = []\n",
    "        for i in range(self.z):\n",
    "            for tf in t_faces:\n",
    "                faces.append(tf.rotate(cq.Vector(0, 0, 0),\n",
    "                                       cq.Vector(0, 0, 1),\n",
    "                                       np.degrees(self.tau * i)))\n",
    "            \n",
    "        shell = cq.Shell.makeShell(faces)\n",
    "        body = cq.Solid.makeSolid(shell)\n",
    "        \n",
    "        bc_r = bottom_pos * np.tan(self.gamma_f)\n",
    "        tc_r = top_pos * np.tan(self.gamma_f)\n",
    "        \n",
    "        b_face = cq.Workplane('XY').workplane(offset=-1.0).circle(bc_r * 1.1).extrude(1.0).val() \n",
    "        t_face = cq.Workplane('XY').workplane(offset=bottom_pos - top_pos).circle(tc_r * 1.1).extrude(1.0).val() \n",
    "        \n",
    "        body = (cq.Workplane('XY').add(body).cut(b_face).cut(t_face))\n",
    "        \n",
    "        arc_x1 = -np.tan(self.gamma_r) * bottom_pos\n",
    "        alpha = np.arctan2(bottom_pos, arc_x1) + np.pi + (self.gamma_f - self.gamma_r)\n",
    "        arc_x2 = -np.cos(alpha) * self.gs_r\n",
    "        arc_y2 = np.sin(alpha) * self.gs_r + bottom_pos\n",
    "                \n",
    "        bt_cut = (cq.Workplane('XZ')\n",
    "                  .moveTo(arc_x1, 0.0)\n",
    "                  .radiusArc((arc_x2, arc_y2), self.gs_r)\n",
    "                  .lineTo(-bc_r, arc_y2)\n",
    "                  .lineTo(-bc_r, 0.0)\n",
    "                  .close()\n",
    "                  .consolidateWires()\n",
    "                  .revolve())\n",
    "        \n",
    "        body = (cq.Workplane('XY').add(body).cut(bt_cut))\n",
    "        \n",
    "        arc_x1 = tc_r + 0.01\n",
    "        arc_y1 = bottom_pos - top_pos\n",
    "        alpha = np.arctan2(-top_pos, arc_x1) - (self.gamma_f - self.gamma_r)\n",
    "        arc_x2 = np.cos(alpha) * (self.gs_r - self.face_width) + 0.01\n",
    "        arc_y2 = np.sin(alpha) * (self.gs_r - self.face_width) + bottom_pos\n",
    "                \n",
    "        tp_cut = (cq.Workplane('XZ')\n",
    "                  .moveTo(0.0, (bottom_pos - top_pos) + 0.01)\n",
    "                  .lineTo(tc_r, (bottom_pos - top_pos) + 0.01)\n",
    "                  .radiusArc((arc_x2, arc_y2), (self.gs_r - self.face_width))\n",
    "                  .lineTo(0.0, arc_y2)\n",
    "                  .close()\n",
    "                  .consolidateWires()\n",
    "                  .revolve())\n",
    "        \n",
    "        body = (cq.Workplane('XY').add(body).cut(tp_cut))\n",
    "        \n",
    "        body = (cq.Workplane('XY').add(body).moveTo(0.0, 0.0).circle(self.bore / 2.0).cutThruAll())\n",
    "        \n",
    "        display = PartGroup(\n",
    "            [\n",
    "                Part(body, 'BevelGear', '#ccf', show_edges=True),\n",
    "            ],\n",
    "            \"BevelGear\"\n",
    "        )\n",
    "        \n",
    "        show(display, axes=True, grid=True, ortho=True, axes0=True, transparent=True)\n",
    "\n",
    "g = BevelGear(module=5.0, teeth_number=13, cone_angle=45.0, face_width=15.0, bore=10.0)\n",
    "\n",
    "g.build()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 391,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "\u001b[0;31mSignature:\u001b[0m \u001b[0mcq\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mShell\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmakeShell\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mlistOfFaces\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mIterable\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mcadquery\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mocc_impl\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mshapes\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mFace\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m->\u001b[0m \u001b[0;34m'Shell'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
       "\u001b[0;31mDocstring:\u001b[0m <no docstring>\n",
       "\u001b[0;31mFile:\u001b[0m      ~/anaconda3/envs/cq21-jl3/lib/python3.8/site-packages/cadquery/occ_impl/shapes.py\n",
       "\u001b[0;31mType:\u001b[0m      method\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "?cq.Shell.makeShell"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "class BevelGearPair:\n",
    "    \n",
    "    def __init__(self, module, gear_teeth, pinion_teeth, face_width,\n",
    "                 axis_angle=90.0, gear_bore=3.0, pinion_bore=3.0,\n",
    "                 pressure_angle=20.0, helix_angle=0.0, addendum_cf=1.0,\n",
    "                 dedendum_cf=1.25, curve_points=16):\n",
    "        \n",
    "        self.axis_angle = axis_angle = np.radians(axis_angle)\n",
    "        \n",
    "        # Cone Angle of the Gear\n",
    "        delta_gear = np.arctan(np.sin(axis_angle) / \\\n",
    "                               (pinion_teeth / gear_teeth + \\\n",
    "                                np.cos(axis_angle)))\n",
    "        \n",
    "        # Cone Angle of the Pinion\n",
    "        delta_pinion = np.arctan(np.sin(axis_angle) / \\\n",
    "                               (gear_teeth / pinion_teeth + \\\n",
    "                                np.cos(axis_angle)))\n",
    "        \n",
    "        self.gear = BevelGear(module, gear_teeth, np.degrees(delta_gear),\n",
    "                              face_width, gear_bore, pressure_angle,\n",
    "                              helix_angle, addendum_cf, dedendum_cf,\n",
    "                              curve_points)\n",
    "        \n",
    "        self.pinion = BevelGear(module, pinion_teeth, np.degrees(delta_pinion),\n",
    "                                face_width, gear_bore, pressure_angle,\n",
    "                                helix_angle, addendum_cf, dedendum_cf,\n",
    "                                curve_points)\n",
    "\n",
    "\n",
    "    def plot(self, plt_axes, omega=0.0,\n",
    "             pitch_circle=False, base_circle=False,\n",
    "             face_circle=False, root_circle=False):        \n",
    "        g_mat = rotation_matrix((0.0, 0.0, 1.0),\n",
    "                                -self.gear.mirrpoint / 2.0 + np.pi \\\n",
    "                                + np.pi / self.gear.z + omega)\n",
    "        \n",
    "        p_omega = -omega * (self.gear.z / self.pinion.z)\n",
    "        p_mat = rotation_matrix((0.0, 0.0, 1.0),\n",
    "                                -self.pinion.mirrpoint / 2.0 + p_omega)\n",
    "        p_mat = p_mat @ rotation_matrix((1.0, 0.0, 0.0), -self.axis_angle)\n",
    "\n",
    "        self.gear.plot(ax, True, pitch_circle, base_circle, face_circle,\n",
    "                       root_circle, g_mat)\n",
    "        self.pinion.plot(ax, False, pitch_circle, base_circle, face_circle,\n",
    "                         root_circle, p_mat)\n",
    "\n",
    "gears = BevelGearPair(module=1.0, gear_teeth=16, pinion_teeth=12, face_width=20.0, axis_angle=120.0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "eafe416b194147259bac58673e991597",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "plt.close()\n",
    "\n",
    "fig = plt.figure()\n",
    "ax = plt.axes(projection='3d')\n",
    "ax.set_xlabel('x')\n",
    "ax.set_ylabel('y')\n",
    "ax.set_zlabel('z')\n",
    "\n",
    "def plot_gears(frame):\n",
    "    ax.clear()\n",
    "    gears.plot(ax, omega=np.pi * 2.0 * (frame / 300.0), pitch_circle=True)\n",
    "\n",
    "gears.plot(ax, pitch_circle=True)\n",
    "# anim = FuncAnimation(fig, plot_gears, 300, interval=100)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 138,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<OCP.TopoDS.TopoDS_Wire object at 0x7f537b91b1b0>\n",
      "<OCP.TopoDS.TopoDS_Shell object at 0x7f537b5cc1f0>\n",
      "Done, using side car 'Gears'\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<jupyter_cadquery.cad_display.CadqueryDisplay at 0x7f537b7cdbe0>"
      ]
     },
     "execution_count": 138,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "r = 2.0\n",
    "\n",
    "t = np.linspace(0.0, np.pi, 20)\n",
    "x1 = np.cos(t * 2.0) * r\n",
    "y1 = np.sin(t * 2.0) * r\n",
    "z1 = t * 3.0\n",
    "\n",
    "x2 = np.cos(np.pi / 2.0 + t * 2.0) * r\n",
    "y2 = np.sin(np.pi / 2.0 + t * 2.0) * r\n",
    "z2 = t * 3.0\n",
    "\n",
    "\n",
    "p1 = np.dstack((x1, y1, z1)).squeeze()\n",
    "p2 = np.dstack((x2, y2, z2)).squeeze()\n",
    "\n",
    "grid = np.stack((p1, p2))\n",
    "\n",
    "f1 = makeSplineApprox(grid)\n",
    "f2 = f1.rotate(cq.Vector(0, 0, 0), cq.Vector(0, 0, 1), 90.0)\n",
    "f3 = f1.rotate(cq.Vector(0, 0, 0), cq.Vector(0, 0, 1), 180.0)\n",
    "f4 = f1.rotate(cq.Vector(0, 0, 0), cq.Vector(0, 0, 1), 270.0)\n",
    "\n",
    "bottom = (cq.Workplane('XY')\n",
    "          .rect(np.sqrt(2 * r ** 2), np.sqrt(2 * r ** 2))\n",
    "          .rotate(cq.Vector(0, 0, 0), cq.Vector(0, 0, 1), 45.0)).val()\n",
    "\n",
    "top = bottom.translate(cq.Vector(0.0, 0.0, np.pi * 3.0))\n",
    "top = cq.Face.makeFromWires(top)\n",
    "bottom = cq.Face.makeFromWires(bottom)\n",
    "\n",
    "sh = cq.Shell.makeShell([bottom, f1, f2, f3, f4, top])\n",
    "print(sh.wrapped)\n",
    "body = cq.Solid.makeSolid(sh)\n",
    "\n",
    "body = (cq.Workplane('XZ')\n",
    "        .add(body)\n",
    "        .moveTo(0.0, np.pi * 3.0 / 2.0)\n",
    "        .circle(0.8)\n",
    "        .cutThruAll())\n",
    "\n",
    "show(body)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 102,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "\u001b[0;31mSignature:\u001b[0m \u001b[0mcq\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSolid\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmakeSolid\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mshell\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mcadquery\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mocc_impl\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mshapes\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mShell\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m->\u001b[0m \u001b[0;34m'Solid'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
       "\u001b[0;31mDocstring:\u001b[0m <no docstring>\n",
       "\u001b[0;31mFile:\u001b[0m      ~/anaconda3/envs/cq21-jl3/lib/python3.8/site-packages/cadquery/occ_impl/shapes.py\n",
       "\u001b[0;31mType:\u001b[0m      method\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "?cq.Solid.makeSolid"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
